#!/usr/bin/env bash
# Installs nginx and configures it on a remote server

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo chown -R $USER:$USER /var/www
sudo chmod -R 755 /var/www/
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
