#!/usr/bin/env bash
# Installs, configures, and starts the server

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
redirect="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "48i $redirect" /etc/nginx/sites-available/default
sudo /etc/init.d/nginx restart
