#!/usr/bin/env bash
#bash script htat creates a file
clean_up_action='rm /var/run/myscript.pid; exit$?'


echo $$ > "/var/run/myscript.pid"
trap 'echo "I hate the kill command"; '"$clean_up_action" SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap ''"$clean_up_action" SIGQUIT

while true; do
	echo "To infinity and beyond"
done
