#!/usr/bin/env bash
#Write a bash script that displays numbers from 1 to 100

for number in {1..100}
do
	if (( number % 3 == 0 && number % 5 == 0))
	then
		echo "FizzBuzz"
	elif ((number % 3 == 0))
	then
		echo "Fizz"
	elif (( number % 5 == 0))
	then
		echo "Buzz"
	else
		echo "$number"
	fi
done
