#!/usr/bin/env bash
#display time for 12 hours amd 59 minutes

hour=0

while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	minute=1
	while [ $minute -le 59 ]
	do
		echo "$minute"
		((minute++))
	done
	((hour++))
done
