#!/usr/bin/env bash
#run nginx as nginx
chmod 777 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill -9 apache
sudo nginx -c "service nginx restart"
